spring:
    jpa:
        database: postgresql
    datasource:
        platform: postgres
        driver-class-name: org.postgresql.Driver
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/portfolio}
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASSWORD:postgres}

logging:
    level:
        org:   
            hibernate:
                SQL: debug
